[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.wp.model.domain.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.wp.model.domain.User" --]
[#-- @ftlvariable name="posts" type="ru.itmo.wp.model.domain.Article[]" --]