[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.web.hw4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.hw4.model.User" --]
[#-- @ftlvariable name="headerselement" type="ru.itmo.web.hw4.model.HeadersElement[]" --]
[#-- @ftlvariable name="currentheaders" type="ru.itmo.web.hw4.model.HeadersElement" --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.hw4.model.Post[]" --]